/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaarmerkingRouteImport } from './routes/waarmerking'
import { Route as ReportoriumRouteImport } from './routes/reportorium'
import { Route as ProtesWasiatRouteImport } from './routes/protes-wasiat'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as LegalisasiRouteImport } from './routes/legalisasi'
import { Route as LaporanBulananRouteImport } from './routes/laporan-bulanan'
import { Route as IndexRouteImport } from './routes/index'

const WaarmerkingRoute = WaarmerkingRouteImport.update({
  id: '/waarmerking',
  path: '/waarmerking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportoriumRoute = ReportoriumRouteImport.update({
  id: '/reportorium',
  path: '/reportorium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtesWasiatRoute = ProtesWasiatRouteImport.update({
  id: '/protes-wasiat',
  path: '/protes-wasiat',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalisasiRoute = LegalisasiRouteImport.update({
  id: '/legalisasi',
  path: '/legalisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanBulananRoute = LaporanBulananRouteImport.update({
  id: '/laporan-bulanan',
  path: '/laporan-bulanan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/laporan-bulanan': typeof LaporanBulananRoute
  '/legalisasi': typeof LegalisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/protes-wasiat': typeof ProtesWasiatRoute
  '/reportorium': typeof ReportoriumRoute
  '/waarmerking': typeof WaarmerkingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laporan-bulanan': typeof LaporanBulananRoute
  '/legalisasi': typeof LegalisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/protes-wasiat': typeof ProtesWasiatRoute
  '/reportorium': typeof ReportoriumRoute
  '/waarmerking': typeof WaarmerkingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/laporan-bulanan': typeof LaporanBulananRoute
  '/legalisasi': typeof LegalisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/protes-wasiat': typeof ProtesWasiatRoute
  '/reportorium': typeof ReportoriumRoute
  '/waarmerking': typeof WaarmerkingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/laporan-bulanan'
    | '/legalisasi'
    | '/pengaturan'
    | '/protes-wasiat'
    | '/reportorium'
    | '/waarmerking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/laporan-bulanan'
    | '/legalisasi'
    | '/pengaturan'
    | '/protes-wasiat'
    | '/reportorium'
    | '/waarmerking'
  id:
    | '__root__'
    | '/'
    | '/laporan-bulanan'
    | '/legalisasi'
    | '/pengaturan'
    | '/protes-wasiat'
    | '/reportorium'
    | '/waarmerking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaporanBulananRoute: typeof LaporanBulananRoute
  LegalisasiRoute: typeof LegalisasiRoute
  PengaturanRoute: typeof PengaturanRoute
  ProtesWasiatRoute: typeof ProtesWasiatRoute
  ReportoriumRoute: typeof ReportoriumRoute
  WaarmerkingRoute: typeof WaarmerkingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waarmerking': {
      id: '/waarmerking'
      path: '/waarmerking'
      fullPath: '/waarmerking'
      preLoaderRoute: typeof WaarmerkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportorium': {
      id: '/reportorium'
      path: '/reportorium'
      fullPath: '/reportorium'
      preLoaderRoute: typeof ReportoriumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protes-wasiat': {
      id: '/protes-wasiat'
      path: '/protes-wasiat'
      fullPath: '/protes-wasiat'
      preLoaderRoute: typeof ProtesWasiatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legalisasi': {
      id: '/legalisasi'
      path: '/legalisasi'
      fullPath: '/legalisasi'
      preLoaderRoute: typeof LegalisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-bulanan': {
      id: '/laporan-bulanan'
      path: '/laporan-bulanan'
      fullPath: '/laporan-bulanan'
      preLoaderRoute: typeof LaporanBulananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaporanBulananRoute: LaporanBulananRoute,
  LegalisasiRoute: LegalisasiRoute,
  PengaturanRoute: PengaturanRoute,
  ProtesWasiatRoute: ProtesWasiatRoute,
  ReportoriumRoute: ReportoriumRoute,
  WaarmerkingRoute: WaarmerkingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
